---
- name: Playbook to run hello world
  hosts: all
  tasks:
    - name: gather-fact-print
      setup:
    - name: create_dir
      ansible.builtin.file:
        path: /home/gtiwari/shivam
        state: directory
